<?php

/**
 * @file
 * The Cookiebot main module file.
 */

/**
 * Implements hook_help().
 */
function cookiebot_help($path, $arg) {
  if ($path !== 'admin/help#cookiebot') {
    return '';
  }

  $output = file_get_contents(backdrop_get_path('module', 'cookiebot') . '/README.md');
  return module_exists('markdown')?
    filter_xss_admin(module_invoke('markdown', 'filter', 'process', 0, -1, $output)) :
    '<pre>' . check_plain($output) . '</pre>';
}

/**
 * Implements hook_menu().
 */
function cookiebot_menu() {
  $items = array();

  $items['admin/config/system/cookiebot'] = array(
    'title' => 'Cookiebot configuration',
    'description' => 'Configure your Cookiebot integration, like the Domain Group ID.',
    'access callback' => 'user_access',
    'access arguments' => array('administer cookiebot'),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('cookiebot_settings_form'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'cookiebot.admin.inc',
  );

  // Add a special menu item for the JavaScript powered Cookiebot renew link.
  // This is not a page that can be visited, but this item makes it possible
  // to place this special link in Backdrop's menus.
  $items['<cookiebot-renew>'] = array(
    'page callback' => 'backdrop_not_found',
    // Since this is a JavaScript only link everybody has access.
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function cookiebot_permission() {
  return array(
    'administer cookiebot' => array(
      'title' => t('Administer Cookiebot Settings'),
      'description' => t('Allows users to administer Cookiebot settings.'),
    ),
    'skip cookiebot consent' => array(
      'title' => t('Can use the site without giving Cookiebot cookie consent'),
      'description' => t('Allows users to use the site without giving Cookiebot cookie consent.'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function cookiebot_theme() {
  return [
    'cookiebot_declaration' => [
      'template' => 'templates/cookiebot-declaration',
      'variables' => [
        'cookiebot_src' => '',
      ],
    ],
    'cookiebot_blocked_element_placeholder' => [
      'template' => 'templates/cookiebot-blocked-element-placeholder',
      'variables' => [
        'content' => NULL,
      ],
    ]
  ];
}

/**
 * Implements hook_config_info().
 */
function cookiebot_config_info() {
  $prefixes['cookiebot.settings'] = array(
    'label' => t('Cookiebot settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_page_alter().
 */
function cookiebot_page_alter(&$page) {
  $config = config('cookiebot.settings');
  if (!_cookiebot_visible()) {
    return;
  }

  $cookiebot_message_placeholder_cookieconsent_optout_marketing = $config->get('cookiebot_message_placeholder_cookieconsent_optout_marketing');
  $message_placeholder_cookieconsent_optout_marketing_build = [
    '#theme' => 'cookiebot_blocked_element_placeholder',
    '#content' => check_markup($cookiebot_message_placeholder_cookieconsent_optout_marketing['value'], $cookiebot_message_placeholder_cookieconsent_optout_marketing['format']),
  ];
  backdrop_add_js([
    'cookiebot' => [
      'message_placeholder_cookieconsent_optout_marketing_show' => $config->get('cookiebot_message_placeholder_cookieconsent_optout_marketing_show') ? TRUE : FALSE,
      'message_placeholder_cookieconsent_optout_marketing' => backdrop_render($message_placeholder_cookieconsent_optout_marketing_build),
    ],
  ], 'setting');
  backdrop_add_library('system', 'jquery.cookie');
  backdrop_add_js(backdrop_get_path('module', 'cookiebot') . '/js/cookiebot.js');
  backdrop_add_css(backdrop_get_path('module', 'cookiebot') . '/css/cookiebot.css', ['every_page' => TRUE]);
}

function cookiebot_preprocess_html(&$variables) {
  $config = config('cookiebot.settings');
  if (!_cookiebot_visible()) {
    return;
  }

  $cbid = $config->get('cookiebot_cbid');
  $attributes = [
    'id' => 'Cookiebot',
    'src' => 'https://consent.cookiebot.com/uc.js',
    'data-cbid' => check_plain($cbid),
  ];

  if ($config->get('cookiebot_block_cookies')) {
    $attributes['data-blockingmode'] = 'auto';
  } else {
    $attributes['async'] = 'async';
  }

  if ($config->get('cookiebot_iab_enabled')) {
    $attributes['data-framework'] = 'IAB';
  }

  $cookiebot = array(
    '#type' => 'markup',
    '#markup' => '<script type="text/javascript" ' . backdrop_attributes($attributes) . '></script>' . "\n",
    '#weight' => -1001,
  );
  backdrop_add_html_head($cookiebot, 'cookiebot_banner');
}

/**
 * Helper function which returns true if cookiebot applies to the current page / session or false if true.
 * Checks for visibulity settings, permissions and other relevant criteria.
 *
 * @return void
 */
function _cookiebot_visible(){
  $config = config('cookiebot.settings');
  global $user;

  $cbid = $config->get('cookiebot_cbid');
  if (empty($cbid)) {
    return FALSE;
  }

  // Check hide if user can use site without giving Cookiebot cookie consent.
  if ($user->uid != 1 && user_access('skip cookiebot consent')) {
    return FALSE;
  }

  // Check hide cookie for the superuser.
  if ($user->uid == 1 && $config->get('cookiebot_exclude_uid_1')) {
    return FALSE;
  }

  // Check exclude paths.
  $cookiebot_exclude_paths = $config->get('cookiebot_exclude_paths');
  if (!empty($cookiebot_exclude_paths)) {
    $path = backdrop_strtolower(backdrop_get_path_alias($_GET['q']));
    // Compare the lowercase internal and lowercase path alias (if any).
    $page_match = backdrop_match_path($path, $cookiebot_exclude_paths);
    if ($path != $_GET['q']) {
      $page_match = $page_match || backdrop_match_path($_GET['q'], $cookiebot_exclude_paths);
    }
    if($page_match){
      return FALSE;
    }
  }

  // Check hide cookie compliance on admin theme.
  if ($config->get('cookiebot_exclude_admin_theme') && path_is_admin(current_path())) {
    return FALSE;
  }

  return TRUE;
}

/**
 * Implements hook_node_view_alter().
 */
function cookiebot_node_view_alter(&$build) {
  $config = config('cookiebot.settings');
  $nid = $build['#node']->nid;
  $declaration_node_id = $config->get('cookiebot_show_declaration_node_id');
  $cbid = $config->get('cookiebot_cbid');

  if (
    $nid != $declaration_node_id || 
    $build['#view_mode'] !== 'full' || 
    empty($cbid) || 
    !$config->get('cookiebot_show_declaration')
  ) {
    return;
  }

  // Print full cookies declaration from Cookiebot.
  $build['cookiebot'] = array(
    '#theme' => 'cookiebot_declaration',
    '#cookiebot_src' => 'https://consent.cookiebot.com/' . $cbid . '/cd.js',
  );
}

/**
 * Implements hook_form_FROM_ID_alter() for menu_edit_item().
 */
function cookiebot_form_menu_edit_item_alter(&$form, &$form_state) {
  if (!isset($form['link_path']['#default_value'])) {
    return;
  }

  $form['link_path']['#description'] .= ' ' . t("Enter '%cookiebot-renew' to generate a link to renew Cookiebot's cookie consent status.", array('%cookiebot-renew' => '<cookiebot-renew>'));
}

/**
 * Implements hook_preprocess_HOOK() for menu_link().
 */
function cookiebot_preprocess_menu_link(&$variables) {
  if (empty($variables['element']['#href']) || $variables['element']['#href'] !== '<cookiebot-renew>') {
    return;
  }

  $variables['element']['#href'] = '/';
  $variables['element']['#localized_options']['attributes']['class'][] = 'cookiebot-renew';
}

/**
 * Implements hook_block_info().
 */
function cookiebot_block_info() {
  $blocks = array();

  $blocks['cookiebot_declaration'] = array(
    'info' => t('Cookiebot declaration'),
    'cache' => BACKDROP_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function cookiebot_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'cookiebot_declaration':
      $cbid = config_get('cookiebot.settings', 'cookiebot_cbid');

      if (empty($cbid)) {
        break;
      }

      $block['content'] = array(
        '#theme' => 'cookiebot_declaration',
        '#cookiebot_src' => 'https://consent.cookiebot.com/' . $cbid . '/cd.js',
      );
      break;
  }

  return $block;
}